name: 'Apt restore state'
description: 'This action will try to restore apt state'
inputs:
  key: 
    description: 'Cache key'
    required: true
    default: apt
runs:
  using: "composite"
  steps:
      - name: Cleanup
        shell: bash
        run: |
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh cache delete apt -R ${{ github.repository }} || :
            for i in /var/{lib/apt/lists,cache/apt/archives}/{partial,lock}; do sudo rm -R "$i" ||: ; done
            for i in {var/{lib,cache},etc}; do mkdir -p "$i" || : ; sudo mv -v {/,}"$i"/apt ; done
      
      - name: Save
        uses: actions/cache/save@v3
        with:
          path: |
            var/lib/apt
            var/cache/apt
            etc/apt
          key: ${{ inputs.key }}

      - name: Postjob
        shell: bash
        run: |
            for i in {var/{lib,cache},etc}; do sudo mv -v {,/}"$i"/apt ; done
